### ISSUE TITLE
Support XML root namespace

### ISSUE THREAD

**Issue by manandre** [Webreaper/CentralisedPackageConverter#14]
For any project file, the XML root namespace `xmlns` attribute is [optional](https://learn.microsoft.com/en-us/visualstudio/msbuild/project-element-msbuild#attributes).
But, when it is present, the file is not processed at all.
For instance, when using this sample project file:
```xml
<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" >
  <ItemGroup>
    <PackageReference Include="TestPackage" Version="1.2.3" />
  </ItemGroup>
</Project>
```
we get the following result:
```
Processing references for D:\temp\cpm\Directory.Build.props...
No versioned references found in csproj files!
Processing Complete.
```
Such project files should be correctly processed.

**Comment by Webreaper** [comment]
Thanks for the fix!
