### ISSUE TITLE
package references with lowercase 'version' tag are ignored

### ISSUE THREAD

**Issue by eliagrady** [Webreaper/CentralisedPackageConverter#18]
To recreate, try running the tool against a csproj with a PackageReference that have a lowercase '**version**' attribute:
i.e:
`<PackageReference Include="morelinq" version="1.4.0" />`

Expected: input version should ignore input version casing and the output should align to Pascal case standard
Actual: PackageReference is skipped

**Comment by Webreaper** [comment]
Fixed.
