### ISSUE TITLE
Better version comparisons 

### ISSUE THREAD

**Issue by Webreaper** [Webreaper/CentralisedPackageConverter#6]
Use [SemanticVersion](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.semanticversion?view=powershellsdk-7.0.0) or [SemVer](https://github.com/maxhauser/semver) for parsing the versions and comparing to see which is higher.

**Comment by davidwengier** [comment]
Use the same logic Nuget uses: https://www.nuget.org/packages/NuGet.Versioning

Hopefully just `NugetVersion.Parse` and then compare

**Comment by Webreaper** [comment]
NIce, thanks.

**Comment by BastianBirke** [comment]
The converter currently picks the lowest version, apart from the string comparison issue ("9.0.0" > "10.0.0"). Is this intended?
You wrote above, and that's what I would normally expect, that it picks the highest.

I am currently trying to integrate NuGet.Versioning _SemanticVersion_, using _.CompareTo()_ and _VersionComparison_.

**Comment by Webreaper** [comment]
I would expect the converter to pick the highest, so if it doesn't that may be a bug. 

Although perhaps it should be a cmdline option - so people can push versions down when consolidating...

**Comment by BastianBirke** [comment]
My last PR #26: changed versioning to _NuGet.Versioning.NuGetVersion_, configurable options. Also switch to pick lowest version (but picks highest by default).
